# Generated by Django 4.0.3 on 2022-06-06 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content_CN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtheme_V_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content_CN.theme_cn')),
            ],
        ),
        migrations.CreateModel(
            name='Video_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('caption', models.TextField(help_text='Enter a caption to be displayed with the image', max_length=1000)),
                ('caption_french', models.TextField(blank=True, default='', help_text='Enter a caption to be displayed with the image', max_length=1000)),
                ('subtheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content_CN.subtheme_v_cn')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content_CN.theme_cn')),
            ],
        ),
        migrations.CreateModel(
            name='subtheme_I_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content_CN.theme_cn')),
            ],
        ),
        migrations.CreateModel(
            name='subtheme_A_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content_CN.theme_cn')),
            ],
        ),
        migrations.CreateModel(
            name='Image_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('caption', models.TextField(help_text='Enter a caption to be displayed with the image', max_length=1000)),
                ('caption_french', models.TextField(blank=True, default='', help_text='Enter a caption to be displayed with the image', max_length=1000)),
                ('subtheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content_CN.subtheme_i_cn')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content_CN.theme_cn')),
            ],
        ),
        migrations.CreateModel(
            name='Audio_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('caption', models.TextField(help_text='Enter a caption to be displayed with the image', max_length=1000)),
                ('caption_french', models.TextField(blank=True, default='', help_text='Enter a caption to be displayed with the image', max_length=1000)),
                ('subtheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content_CN.subtheme_a_cn')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content_CN.theme_cn')),
            ],
        ),
    ]
