# Generated by Django 4.0.3 on 2022-04-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0003_rename_video_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
