# Generated by Django 4.0.3 on 2022-04-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0006_rename_sub_theme_subtheme_subtheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sub_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subthemes', to='media_content.subtheme'),
        ),
        migrations.AlterField(
            model_name='image',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='media_content.theme'),
        ),
    ]
