# Generated by Django 4.0.3 on 2022-04-25 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0012_remove_video_theme_alter_image_subtheme_delete_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='subtheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.subtheme'),
        ),
        migrations.AlterField(
            model_name='image',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.theme'),
        ),
    ]
