# Generated by Django 4.0.3 on 2022-04-27 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0014_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subTheme',
            new_name='subtheme_I',
        ),
        migrations.CreateModel(
            name='subtheme_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.theme')),
            ],
        ),
        migrations.CreateModel(
            name='subtheme_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('caption', models.TextField(help_text='Enter a caption to be displayed with the image', max_length=1000)),
                ('subtheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.subtheme_a')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.theme')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='subtheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.subtheme_v'),
        ),
    ]
