# Generated by Django 4.0.3 on 2022-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0016_rename_path_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='caption_french',
            field=models.TextField(blank=True, default='', help_text='Enter a caption to be displayed with the image', max_length=1000),
        ),
        migrations.AddField(
            model_name='image',
            name='caption_french',
            field=models.TextField(blank=True, default='', help_text='Enter a caption to be displayed with the image', max_length=1000),
        ),
        migrations.AddField(
            model_name='video',
            name='caption_french',
            field=models.TextField(blank=True, default='', help_text='Enter a caption to be displayed with the image', max_length=1000),
        ),
    ]
