# Generated by Django 4.0.3 on 2022-04-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a theme (e.g. Entertainment)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('sub_theme', models.CharField(max_length=200)),
                ('caption', models.TextField(help_text='Enter a caption to be displayed with the image', max_length=1000)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.theme')),
            ],
        ),
    ]
