# Generated by Django 4.0.3 on 2022-04-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0005_subtheme_alter_image_sub_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtheme',
            old_name='sub_theme',
            new_name='subTheme',
        ),
    ]
