# Generated by Django 4.0.3 on 2022-04-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0013_alter_image_subtheme_alter_image_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('caption', models.TextField(help_text='Enter a caption to be displayed with the image', max_length=1000)),
                ('subtheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media_content.subtheme')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.theme')),
            ],
        ),
    ]
