# Generated by Django 4.0.3 on 2022-04-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0015_rename_subtheme_subtheme_i_subtheme_v_subtheme_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='path',
            new_name='url',
        ),
    ]
