# Generated by Django 4.0.3 on 2022-04-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0002_video_audio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
