# Generated by Django 4.0.3 on 2022-04-24 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0007_alter_image_sub_theme_alter_image_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sub_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subTheme', to='media_content.image'),
        ),
    ]
