# Generated by Django 4.0.3 on 2022-04-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0008_alter_image_sub_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sub_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTheme', to='media_content.image'),
        ),
    ]
