# Generated by Django 4.0.3 on 2022-04-25 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0010_alter_image_sub_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='sub_theme',
            new_name='subtheme',
        ),
        migrations.RenameField(
            model_name='subtheme',
            old_name='subTheme',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='sub_theme',
            new_name='subtheme',
        ),
        migrations.RemoveField(
            model_name='image',
            name='sub_theme',
        ),
        migrations.AddField(
            model_name='image',
            name='subtheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media_content.subtheme', unique=True),
        ),
    ]
