# Generated by Django 4.0.3 on 2022-04-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0011_rename_sub_theme_audio_subtheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='theme',
        ),
        migrations.AlterField(
            model_name='image',
            name='subtheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtheme', to='media_content.subtheme'),
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
